apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment_name }}
spec:
  selector:
    app: {{ .Values.selector_label }}
  type: ClusterIP
  ports:
    - name: tomcat
      protocol: TCP
      targetPort: {{ .Values.targetport }}
      port: {{ .Values.port }}
